### ISSUE TITLE
stuck after post_install_test.sh

### ISSUE THREAD

**Issue by dgkurt** [santirdnd/COPLA#7]
Using the yml file, post_install_test.sh does not work. It stops 
`copla$ bin/post_install_test.sh`

With this output
```
Checking for bash ...
  OK - Current version: 5.0.17(1)-release
Checking for conda ...
  OK - Current version: 4.9.2
Checking for perl ...
  OK - Current version: v5.26.2
Checking for python3 ...
  OK - Current version: 3.9.7
Checking for graph_tool ...
  OK - Current version: 2.43
Checking for numpy ...
  OK - Current version: 1.21.2
Checking for pandas ...
  OK - Current version: 1.3.2
Checking for blastn ...
  OK - Current version: 2.12.0+
Checking for prodigal ...
  OK - Current version: 2.6.3
Checking for hmmscan ...
  OK - Current version: 3.3.2
Checking for plasmidfinder.py ...
  OK
Checking for macsyfinder ...
  OK - Current version: 1.0.5
Checking for ruby ...
  OK - Current version: 2.7.2p137
Checking for parallel ...
  OK - Current version: 20210822
Checking for ani.rb ...
  OK
Checking COPLA with plasmid NZ_CP028167.1 ...

/home/dgkurt/miniconda3/envs/copla/lib/python3.9/site-packages/graph_tool/inference/blockmodel.py:387: UserWarning: unrecognized keyword arguments: ['sampling']
  warnings.warn("unrecognized keyword arguments: " +

```
Installation with the alternative went well
`conda create --file copla.spec-file.txt -n copla`
I think the issue could be in the newer version
``Checking for graph_tool ...
  OK - Current version: 2.43
``

**Comment by MariaBalbuena** [comment]
I had the same issue. I solved it  to changed the version of graph-tool 2.44 for graph-tool 2.33

**Comment by mweedim** [comment]
I had the same issue. When first used, the graph_tool version of the default installation was 2.44 and when reinstalled with copla.spec-file.txt, it was 2.35
But the problem is not solved

**Comment by SGarciaCobos** [comment]
Hi,
I have the same problem, post_install_test.sh does not work, even when using the alternative for installation `conda create --file copla.spec-file.txt -n copla`

This is the output I get:

 ````
OK - Current version: 5.0.17(1)-release
Checking` for conda ...
 OK - Current version: 4.10.3
Checking for perl ...
  OK - Current version: v5.26.2
Checking for python3 ...
  OK - Current version: 3.9.0
Checking for graph_tool ...
  OK - Current version: 2.35
Checking for numpy ...
  OK - Current version: 1.19.4
Checking for pandas ...
  OK - Current version: 1.1.5
Checking for blastn ...
  OK - Current version: 2.10.1+
Checking for prodigal ...
  OK - Current version: 2.6.3
Checking for hmmscan ...
  OK - Current version: 3.3.1
Checking for plasmidfinder.py ...
  OK
Checking for macsyfinder ...
  OK - Current version: 1.0.5
Checking for ruby ...
ruby: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
  OK - Current version: 2.3
Checking for parallel ...
  OK - Current version: 20220722
Checking for ani.rb ...
  OK
Checking COPLA with plasmid NZ_CP028167.1 ...

Traceback (most recent call last):
  File "bin/copla.py", line 12, in <module>
    import graph_tool.all as gt
  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/dl_import.py", line 58, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: /home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/libgraph_tool_core.so: undefined symbol: _ZN5boost9iostreams4zlib6finishE

  Error! Output for plasmid NZ_CP028167.1 differs. Please verify COPLA installation
Checking COPLA with plasmid NZ_CP028329.1 ...

Traceback (most recent call last):
  File "bin/copla.py", line 12, in <module>
    import graph_tool.all as gt
  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/dl_import.py", line 58, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: /home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/libgraph_tool_core.so: undefined symbol: _ZN5boost9iostreams4zlib6finishE
``` `

**Comment by missyoudaisy** [comment]
> Hi, I have the same problem, post_install_test.sh does not work, even when using the alternative for installation `conda create --file copla.spec-file.txt -n copla`
> 
> This is the output I get:
> 
> ```
> OK - Current version: 5.0.17(1)-release
> Checking` for conda ...
> OK - Current version: 4.10.3
> Checking for perl ...
>  OK - Current version: v5.26.2
> Checking for python3 ...
>  OK - Current version: 3.9.0
> Checking for graph_tool ...
>  OK - Current version: 2.35
> Checking for numpy ...
>  OK - Current version: 1.19.4
> Checking for pandas ...
>  OK - Current version: 1.1.5
> Checking for blastn ...
>  OK - Current version: 2.10.1+
> Checking for prodigal ...
>  OK - Current version: 2.6.3
> Checking for hmmscan ...
>  OK - Current version: 3.3.1
> Checking for plasmidfinder.py ...
>  OK
> Checking for macsyfinder ...
>  OK - Current version: 1.0.5
> Checking for ruby ...
> ruby: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
>  OK - Current version: 2.3
> Checking for parallel ...
>  OK - Current version: 20220722
> Checking for ani.rb ...
>  OK
> Checking COPLA with plasmid NZ_CP028167.1 ...
> 
> Traceback (most recent call last):
>  File "bin/copla.py", line 12, in <module>
>    import graph_tool.all as gt
>  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/__init__.py", line 106, in <module>
>    dl_import("from . import libgraph_tool_core as libcore")
>  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/dl_import.py", line 58, in dl_import
>    exec(import_expr, local_dict, global_dict)
>  File "<string>", line 1, in <module>
> ImportError: /home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/libgraph_tool_core.so: undefined symbol: _ZN5boost9iostreams4zlib6finishE
> 
>  Error! Output for plasmid NZ_CP028167.1 differs. Please verify COPLA installation
> Checking COPLA with plasmid NZ_CP028329.1 ...
> 
> Traceback (most recent call last):
>  File "bin/copla.py", line 12, in <module>
>    import graph_tool.all as gt
>  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/__init__.py", line 106, in <module>
>    dl_import("from . import libgraph_tool_core as libcore")
>  File "/home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/dl_import.py", line 58, in dl_import
>    exec(import_expr, local_dict, global_dict)
>  File "<string>", line 1, in <module>
> ImportError: /home/silvia/miniconda3/envs/copla/lib/python3.8/site-packages/graph_tool/libgraph_tool_core.so: undefined symbol: _ZN5boost9iostreams4zlib6finishE
> ``` `
> ```

How do you solve the problem?

**Comment by rpalcab** [comment]
Hello all,

I've followed @MariaBalbuena solution and it worked. I've downgraded Python version to 3.8.0 and installed the packages python_abi=3.8.0 and graph-tool=2.33 (command ```conda install python=3.8.0 python_abi=3.8.0 graph-tool=2.33```)

Hope it works if anyone is still experiencing the problem.
